/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    public static void main(String[] args) {
        ObjectMapper mapper = new ObjectMapper();
        try {
            System.out.println("Serialization");
            User user = new User("Alvin", 21);
            System.out.println(mapper.writeValueAsString(user));
            System.out.println("Deserialization");
            String jsonToConvert = new String("{\"name\":\"Jane Doe\",\"age\":25}");
            User deserializedUser = mapper.readValue(jsonToConvert, User.class);
            System.out.println(deserializedUser);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
